# RabbitMQ Configuration
management.load_definitions = /etc/rabbitmq/definitions.json

# Logging
log.console = true
log.console.level = info

# Default limits
vm_memory_high_watermark.relative = 0.7
disk_free_limit.relative = 1.5
